#!/bin/bash

#Here I am just going to put some prerequisites so they don't get lost:

# a directory at usr/share/spacewalk pulling newest git content from a public repo (this is the repo where this script lives)
# lnxrouter script is just copied into this repo, with one modification: I've added dnsmasq property to resolve ALL DNS requests to local ip
# nginx with a modified config to include all additional config files from spacewalk directory
# nodogsplash, which doesn't have a package and has to be built on the device
# unofficial wiringpi, because the official one doesn't work with all raspis https://github.com/WiringPi/WiringPi/releases/tag/2.61-1
# use jq to make edit some of the jsons from bash
# install moreutils to get the sponge command
# install php8.1-fpm so that nginx can serve php

echo "Space Walk Startup Script Running"
echo $PWD
#First we read the Gpio to determine the mode


mode="all"
if (($(gpio read 0) == 1)); then
    mode="stage1"
elif (($(gpio read 2) == 1)); then
    mode="stage2"
elif (($(gpio read 3) == 1)); then
    mode="stage3"
fi

echo "Detected mode $mode"

#Then we do a git pull to get all the latest content if parameter for git is available
for var in "$@"
do
    if [[ $var == "gitupdate"]]; then
        sudo git stash
        sudo git pull
    fi
done

sudo rm -r conf.d/*

#we store the mode in variables for website that need it
case $mode in

    all)
        sudo cat variables.json | jq '.mode = $v' --arg v -1 | sponge variables.json
        ;;

    stage1)
        sudo cat variables.json | jq '.mode = $v' --arg v 0 | sponge variables.json
        ;;

    stage2)
        sudo cat variables.json | jq '.mode = $v' --arg v 1 | sponge variables.json
        ;;

    stage3)
        sudo cat variables.json | jq '.mode = $v' --arg v 2 | sponge variables.json
        ;;

esac

#First copy the splash pages to nodgosplash directory (couldn't find a way to change where it is served from, but keeping the original copy in repo /splash )
case $mode in

    stage1)
        sudo cp -a stage1websites/splash/. /etc/nodogsplash/htdocs/
        ;;

    stage2)
        sudo cp -a stage2websites/splash/. /etc/nodogsplash/htdocs/
        ;;

    stage3)
        sudo cp -a stage3websites/splash/. /etc/nodogsplash/htdocs/
        ;;

esac

#Then copy the correct nginx configs
case $mode in

    stage1)
        sudo cp -a nginx_conf_files/stage1/. conf.d/
        ;;

    stage2)
        sudo cp -a nginx_conf_files/stage2/. conf.d/
        ;;

    stage3)
        sudo cp -a nginx_conf_files/stage3/. conf.d/
        ;;

    all)
        sudo cp -a nginx_conf_files/stage1/. conf.d/
        sudo cp -a nginx_conf_files/stage2/. conf.d/
        sudo cp -a nginx_conf_files/stage3/. conf.d/        

esac

#Copy stage-independent configs
sudo cp nginx_conf_files/default.conf conf.d/
sudo cp -a nginx_conf_files/universal/. conf.d/

#once everything is in place - we start the ap
sudo lnxrouter --ap wlan0 SpaceWalkGame --dns-nocache -g 192.168.5.1 -d -n --daemon

#ap takes a bit of time to setup so we have to wait, the captive portal needs it running before it starts
sleep 10
sudo nodogsplash

#wait a bit more for good measure and start the webservers
sleep 5
sudo systemctl restart nginx

#Setup script is done
echo "Space walk startup script finished"
exit 0