#!/bin/bash

#Here I am just going to put some prerequisites so they don't get lost:

#a directory at usr/share/spacewalk pulling newest git content from a public repo (this is the repo where this script lives)
#lnxrouter script is just copied into this repo, with one modification: I've added dnsmasq property to resolve ALL DNS requests to local ip
#nginx with a modified config to include all additional config files from spacewalk directory
#nodogsplash, which doesn't have a package and has to be built on the device
#unofficial wiringpi, because the official one doesn't work with all raspis https://github.com/WiringPi/WiringPi/releases/tag/2.61-1

echo "Space Walk Startup Script Running"
echo $PWD


#First we read the Gpio to determine the mode
mode1=$(gpio read 0)
mode2=$(gpio read 2)
mode3=$(gpio read 3)
modeAll=0
if (($mode1 == 0)) && (($mode2 == 0)) && (($mode3 == 0)); then
    modeAll=1
fi

echo "mode1 $mode1"
echo "mode2 $mode2"
echo "mode3 $mode3"
echo "modeAll $modeAll"


#Then we do a git pull to get all the latest content
#sudo git pull

#Then based on the mode, we copy stuff around


#First copy the splash


#Second copy persistent pages data


#Then copy the correct nginx configs


#once everything is in place - we start the ap, splash server and webservers
#sudo lnxrouter --ap wlan0 SpaceWalkGame  --dns-nocache -g 192.168.1.5 -d -n --daemon
#sudo nodogsplash
#sudo nginx